### PR TITLE
Dark theme (Beta)

### PR DESCRIPTION
**Pull request by 1ctinus**
Tried to make a dark theme, can be found under a media query. Right now, there is no toggle. I have also added 5 transparent icons to see if they are better than the original, and if I should keep making them.
image
image

### CODE REVIEW

**Comment by 1ctinus** [comment]
will this be added @ACMerriman ? sorry if bumping annoys you.

**Comment by ACMerriman** [comment]
I don't plan to add it in its current form. I may consider adding it once the toggle is included but I won't make promises. Also I think the logos look better with the white background.

**Comment by 1ctinus** [comment]
Fair. I agree with both. I will work on a toggle

**Comment by 1ctinus** [comment]
I forgot about this. sorry

**Pull request closed without merging**
